PXS/PXS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('ui.urls')),
    path('admin/', admin.site.urls),
]

PXS/ui/urls.py
""" URLs """
from django.urls import path, re_path

from . import views

app_name = 'ui'
urlpatterns = [
    path('', views.index, name='index'),
    path('ranking', views.ranking, name='ranking'),
    path('country/<int:id>', views.country, name='country'),
    path('country/<int:id>/cantons', views.countryCantons, name='countryCantons'),
    path('canton/<int:id>', views.canton, name='canton'),
    path('canton/<int:id>/cities', views.cantonCities, name='cantonCities'),
    path('canton/<int:id>/polygon', views.cantonPolygon, name='cantonPolygon'),
    path('city/<int:id>', views.city, name='city'),
    path('city/<int:id>/polygon', views.cityPolygon, name='cityPolygon'),
    path('polygon', views.polygon, name='polygon'),
    path('polygon/stats', views.polygonStats, name='polygonStats'),
    re_path(r'^tile/(?P<z>[0-9]+)/(?P<x>[0-9]+)/(?P<y>[0-9]+).png$', views.tile, name='tile')
]

PXS/ui/models.py
""" Models """
from django.contrib.gis.db import models
from django.db.models import Window, F
from django.db.models.functions import RowNumber

class Tile(models.Model):
    """ Tile model """
    x = models.IntegerField()
    y = models.IntegerField()
    index = models.IntegerField()
    tree_density = models.FloatField()
    tree_sparsity = models.FloatField()

    mpoly = models.GeometryField(null=True, srid=4326, geography=True)

    def __str__(self):
        return 'tile/{}-{}-{}-{}'.format(self.pk, self.x, self.y, self.index)

class Country(models.Model):
    """ Country model """
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    population = models.IntegerField(null=True)
    area = models.FloatField(null=True)
    cars = models.IntegerField(null=True)

    mpoly = models.GeometryField(null=True, srid=4326, geography=True)

    score = models.FloatField(null=True)
    tree_density = models.FloatField(null=True)
    tree_sparsity = models.FloatField(null=True)
    has_mapping = models.BooleanField(default=False)

    def get_rank(self):
        ranked_countries = Country.objects.exclude(score__isnull=True).annotate(rank=Window(expression=RowNumber(), order_by=[F('score').desc()]))
        for country in ranked_countries:
            if country.pk == self.pk:
                return country.rank
        return None

    def __str__(self):
        return 'country/{}'.format(self.name)

class Canton(models.Model):
    """ Canton model """
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    population = models.IntegerField(null=True)
    area = models.FloatField(null=True)
    cars = models.IntegerField(null=True)

    mpoly = models.GeometryField(null=True, srid=4326, geography=True)

    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)

    score = models.FloatField(null=True)
    tree_density = models.FloatField(null=True)
    tree_sparsity = models.FloatField(null=True)
    has_mapping = models.BooleanField(default=False)

    def get_rank(self):
        ranked_cantons = Canton.objects.exclude(score__isnull=True).annotate(rank=Window(expression=RowNumber(), order_by=[F('score').desc()]))
        for canton in ranked_cantons:
            if canton.pk == self.pk:
                return canton.rank
        return None

    def get_relative_population(self):
        nr_of_country_cities = self.country.city_set.count()
        rel_population = self.population / self.country.population
        return rel_population

    def get_relative_area(self):
        nr_of_country_cities = self.country.city_set.count()
        rel_area = self.area / self.country.area
        return rel_area

    def get_cars_pp(self):
        cars_pp = self.cars / self.population
        return cars_pp

    def __str__(self):
        return 'canton/{}'.format(self.name)

class City(models.Model):
    """ City model """
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    population = models.IntegerField(null=True)
    area = models.FloatField(null=True)
    cars = models.IntegerField(null=True)

    mpoly = models.GeometryField(null=True, srid=4326, geography=True)

    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    canton = models.ForeignKey(Canton, on_delete=models.CASCADE, null=True)

    score = models.FloatField(null=True)
    tree_density = models.FloatField(null=True)
    tree_sparsity = models.FloatField(null=True)
    has_mapping = models.BooleanField(default=False)

    def get_rank(self):
        ranked_cities = City.objects.exclude(score__isnull=True).annotate(rank=Window(expression=RowNumber(), order_by=[F('score').desc()]))
        for city in ranked_cities:
            if city.pk == self.pk:
                return city.rank
        return None

    def get_relative_population(self):
        nr_of_country_cities = self.country.city_set.count()
        rel_population = self.population / self.country.population
        return rel_population

    def get_relative_area(self):
        nr_of_country_cities = self.country.city_set.count()
        rel_area = self.area / self.country.area
        return rel_area

    def get_cars_pp(self):
        cars_pp = self.cars / self.population
        return cars_pp

    def __str__(self):
        return 'city/{}'.format(self.name)

PXS/ui/views.py
import os
import json
import numpy as np
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import HttpResponse, Http404, JsonResponse
from django.core.serializers import serialize
from django.views.decorators.http import require_http_methods
from django.views.decorators.cache import cache_page
from django.db.models.functions import Cast
from django.db.models.aggregates import Avg, Sum
from django.contrib.gis.db.models import GeometryField
from django.contrib.gis.db.models.functions import Area
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.staticfiles.templatetags.staticfiles import static
from ui import functions, models


# Create your views here.
def index(request):
    return render(request, 'pxs/index.html')

def ranking(request):
    return render(request, 'pxs/ranking.html')

@require_http_methods(["GET"])
@cache_page(60*60)
def country(request, id):
    response = {}
    country = models.Country.objects.filter(id=id).first()
    if country:
        response = json.loads(serialize('json', [country], fields=('pk', 'name', 'tree_density', 'score', 'has_mapping')))[0]
        response['fields']['rank'] = country.get_rank()
    return JsonResponse(response)

@require_http_methods(["GET"])
@cache_page(60*60)
def countryCantons(request, id):
    response = {}
    country = models.Country.objects.filter(id=id).first()
    if country:
        response = json.loads(serialize('geojson', country.canton_set.all(), fields=('pk', 'name', 'mpoly', 'has_mapping', 'score')))
    return JsonResponse(response)

@require_http_methods(["GET"])
@cache_page(60*60)
def canton(request, id):
    response = {}
    canton = models.Canton.objects.filter(id=id).first()
    if canton:
        response = json.loads(serialize('json', [canton], fields=('pk', 'name', 'tree_density', 'tree_sparsity', 'score', 'has_mapping')))[0]
        response['fields']['rank'] = canton.get_rank()
        response['fields']['rel_population'] = canton.get_relative_population()
        response['fields']['rel_area'] = canton.get_relative_area()
        response['fields']['cars_pp'] = canton.get_cars_pp()
    return JsonResponse(response)

@require_http_methods(["GET"])
@cache_page(60*60)
def cantonCities(request, id):
    response = {}
    canton = models.Canton.objects.filter(id=id).first()
    if canton:
        response = json.loads(serialize('geojson', canton.city_set.all(), fields=('pk', 'name', 'mpoly', 'has_mapping', 'score')))
    return JsonResponse(response)

@require_http_methods(["GET"])
@cache_page(60*60)
def city(request, id):
    response = {}
    city = models.City.objects.filter(id=id).first()
    if city:
        response = json.loads(serialize('json', [city], fields=('pk', 'name', 'tree_density', 'tree_sparsity', 'score', 'has_mapping')))[0]
        response['fields']['rank'] = city.get_rank()
        response['fields']['rel_population'] = city.get_relative_population()
        response['fields']['rel_area'] = city.get_relative_area()
        response['fields']['cars_pp'] = city.get_cars_pp()
    return JsonResponse(response)

@require_http_methods(["GET"])
@cache_page(60*60)
def polygon(request):
    param = request.GET.get('geojson', None)
    if not param:
        raise Http404
    parsed_geojson = json.loads(param)
    geometry = GEOSGeometry(json.dumps(parsed_geojson['geometry']))
    tiles = models.Tile.objects \
        .annotate(geom=Cast('mpoly', GeometryField())) \
        .filter(geom__within=geometry)
    densities = []
    for tile in tiles:
        centroid = tile.mpoly.centroid
        densities.append({'x': centroid.x, 'y': centroid.y, 'value': tile.tree_density})
    polygon = functions.get_polygon(parsed_geojson['geometry'], densities=densities)
    response = HttpResponse(content_type='image/png')
    polygon.save(response, 'PNG')
    return response
    
@require_http_methods(["GET"])
@cache_page(60*60)
def polygonStats(request):
    param = request.GET.get('geojson', None)
    if not param:
        raise Http404
    response = {}
    parsed_geojson = json.loads(param)
    geometry = GEOSGeometry(json.dumps(parsed_geojson['geometry']))
    country = models.Country.objects \
        .annotate(geom=Cast('mpoly', GeometryField())) \
        .filter(geom__contains=geometry) \
        .first()
    if country:
        metrics = models.Tile.objects \
            .annotate(geom=Cast('mpoly', GeometryField())) \
            .filter(geom__within=geometry) \
            .aggregate(Avg('tree_density'), Avg('tree_sparsity'), Sum(Area('mpoly')))
        tree_density = 0
        tree_sparsity = 0
        weights = [
            160, # Tree coverage
            240, # Tree sparsity
            2 # Relative area
        ]
        if metrics['tree_density__avg']: # Check if result returned, a.k.a has tiles
            tree_density = metrics['tree_density__avg']
            tree_sparsity = metrics['tree_sparsity__avg']
            rel_area = metrics['Area__sum'].sq_m / country.area
            score = np.dot(weights, [
                tree_density,
                functions.sparsity_to_representable(tree_sparsity),
                rel_area
            ])
            response['tree_density'] = tree_density
            response['tree_sparsity'] = tree_sparsity
            response['rel_area'] = rel_area
            response['score'] = score
    return JsonResponse(response)

@require_http_methods(["GET"])
@cache_page(60*60)
def cityPolygon(request, id):
    item = models.City.objects.filter(id=id).first()
    if item is None:
        raise Http404
    cached_url = os.path.join(settings.BASE_DIR, 'ui', 'static', 'pxs', 'cities', '{}.png'.format(item.pk))
    if os.path.isfile(cached_url):
        response = HttpResponse(content_type='image/png')
        functions.read_image(cached_url).save(response, 'PNG')
        return response
    tiles = models.Tile.objects \
        .annotate(geom=Cast('mpoly', GeometryField())) \
        .filter(geom__within=item.mpoly)
    densities = []
    for tile in tiles:
        centroid = tile.mpoly.centroid
        densities.append({'x': centroid.x, 'y': centroid.y, 'value': tile.tree_density})
    polygon = functions.get_polygon(json.loads(item.mpoly.json), densities=densities)
    response = HttpResponse(content_type='image/png')
    polygon.save(cached_url, 'png')
    polygon.save(response, 'PNG')
    return response

@require_http_methods(["GET"])
@cache_page(60*60)
def cantonPolygon(request, id):
    item = models.Canton.objects.filter(id=id).first()
    if item is None:
        raise Http404
    cached_url = os.path.join(settings.BASE_DIR, 'ui', 'static', 'pxs', 'cantons', '{}.png'.format(item.pk))
    if os.path.isfile(cached_url):
        response = HttpResponse(content_type='image/png')
        functions.read_image(cached_url).save(response, 'PNG')
        return response
    tiles = models.Tile.objects \
        .annotate(geom=Cast('mpoly', GeometryField())) \
        .filter(geom__within=item.mpoly)
    densities = []
    for tile in tiles:
        centroid = tile.mpoly.centroid
        densities.append({'x': centroid.x, 'y': centroid.y, 'value': tile.tree_density})
    polygon = functions.get_polygon(json.loads(item.mpoly.json), densities=densities)
    response = HttpResponse(content_type='image/png')
    polygon.save(cached_url, 'png')
    polygon.save(response, 'PNG')
    return response

def tile(request, x, y, z):
    real_url = '/static/pxs/tiles/{}/{}/{}.png'.format(z, x, y)
    return redirect(real_url, permanent=False)

PXS/ui/templates/pxs/base.html
{% load static %}
{% load compile_static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>PXS 2018</title>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.0/dist/leaflet.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
            integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
            crossorigin="anonymous" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet.pm@latest/dist/leaflet.pm.css" />
        <link rel="stylesheet" type="text/css" href="{% static 'pxs/css/main.scss'|compile %}" />


        <script
            src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
        <script src="https://unpkg.com/leaflet@1.0.0/dist/leaflet.js"></script>
        <script src="https://unpkg.com/leaflet.pm@latest/dist/leaflet.pm.min.js"></script>
        <script src="{% static 'pxs/js/leaflet-geodesy.js' %}"></script>
        <script src="{% static 'pxs/js/main.js' %}"></script>
        <script src="{% static 'pxs/js/map.js' %}"></script>
    </head>
    <body>
        {% include "pxs/menu.html" %}
        <div id="content">
            {% block content %}{% endblock %}
        </div>
        {% include "pxs/map.html" %}
    </body>
</html>

PXS/ui/templates/pxs/index.html
{% extends "pxs/base.html" %}

{% load static %}

{% block content %}
    <div id="scale-chooser">
        <div class="placeholder"></div>
        <div class="buttons">
            <a href="#canton" class="option" data-state="canton">
                Canton
            </a>
            <a href="#city" class="option selected" data-state="city">
                City
            </a>
            <a href="#area" class="option" data-state="area">
                Area
            </a>
        </div>
        <div class="switcher" data-state="map">
            <a href="#">Statistics <i class="fas fa-toggle-on"></i> Map</a>
        </div>
    </div>
    <div id="stat-compare-wrapper">
        <div class="stat-compare-names">
            <div class="name left"><span>-</span></div>
            <div class="name middle"><span><i class="fas fa-arrows-alt-h"></i></span></div>
            <div class="name right"><span>-</span></div>
        </div>
        <div class="stat-compare-scores">
            <div class="score left"><span>0</span></div>
            <div class="score middle"></div>
            <div class="score right"><span>0</span></div>
        </div>
        <div class="stat-compare">
            <div class="stat-wrapper density">
                <div class="stat-inner-wrapper">
                    <div class="stat-last-wrapper">
                        <div class="stat-number left">-</div>
                        <div class="stat first left"></div>
                    </div>
                    <div class="stat-last-wrapper">
                        <div class="stat-number right">-</div>
                        <div class="stat first right"></div>
                    </div>
                </div>
                <div class="stat-name"><span>Tree density</span></div>
            </div>
            <div class="stat-wrapper sparsity">
                <div class="stat-inner-wrapper">
                    <div class="stat-last-wrapper">
                        <div class="stat-number left">-</div>
                        <div class="stat first left"></div>
                    </div>
                    <div class="stat-last-wrapper">
                        <div class="stat-number right">-</div>
                        <div class="stat first right"></div>
                    </div>
                </div>
                <div class="stat-name"><span>Tree sparsity</span></div>
            </div>
            <div class="stat-wrapper cars">
                <div class="stat-inner-wrapper">
                    <div class="stat-last-wrapper">
                        <div class="stat-number left">-</div>
                        <div class="stat first left"></div>
                    </div>
                    <div class="stat-last-wrapper">
                        <div class="stat-number right">-</div>
                        <div class="stat first right"></div>
                    </div>
                </div>
                <div class="stat-name"><span>Cars per inhabitant</span></div>
            </div>
            <div class="stat-wrapper area">
                <div class="stat-inner-wrapper">
                    <div class="stat-last-wrapper">
                        <div class="stat-number left">-</div>
                        <div class="stat first left"></div>
                    </div>
                    <div class="stat-last-wrapper">
                        <div class="stat-number right">-</div>
                        <div class="stat first right"></div>
                    </div>
                </div>
                <div class="stat-name"><span>Relative area</span></div>
            </div>
            <div class="stat-wrapper population">
                <div class="stat-inner-wrapper">
                    <div class="stat-last-wrapper">
                        <div class="stat-number left">-</div>
                        <div class="stat first left"></div>
                    </div>
                    <div class="stat-last-wrapper">
                        <div class="stat-number right">-</div>
                        <div class="stat first right"></div>
                    </div>
                </div>
                <div class="stat-name"><span>Relative population</span></div>
            </div>
        </div>
    </div>
    <div id="splitscreen">
        <div class="field">
            <div class="map">
                <div class="map-image-wrapper" data-side="left">
                    <div class="desc">
                        <i class="fas fa-plus"></i><br />Choose an area
                    </div>
                </div>
                <div id="real-map-left"></div>
            </div>
            <div class="stats-container">
                <div class="name" data-side="left">
                    <span>Choose an area</span>
                </div>
                <div class="stats" data-side="left">
                    <div class="stat" data-type="rank">
                        <div class="number">
                            -
                        </div>
                        <div class="description">
                            place in city ranking
                        </div>
                    </div>
                    <div class="stat" data-type="tree-coverage">
                        <div class="number">
                            -
                        </div>
                        <div class="description">
                            percentage tree coverage
                        </div>
                    </div>
                    <div class="stat" data-type="score">
                        <div class="number">
                            -
                        </div>
                        <div class="description">
                            overall city score
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="field">
            <div class="map">
                <div class="map-image-wrapper" data-side="right">
                    <div class="desc">
                        <i class="fas fa-plus"></i><br />Choose an area
                    </div>
                </div>
                <div id="real-map-right"></div>
            </div>
            <div class="stats-container">
                <div class="name" data-side="right">
                    <span>Choose an area</span>
                </div>
                <div class="stats" data-side="right">
                    <div class="stat" data-type="rank">
                        <div class="number">
                            -
                        </div>
                        <div class="description">
                            place in city ranking
                        </div>  
                    </div>
                    <div class="stat" data-type="tree-coverage">
                        <div class="number">
                            -
                        </div>
                        <div class="description">
                            percentage tree coverage
                        </div>
                    </div>
                    <div class="stat" data-type="score">
                        <div class="number">
                            -
                        </div>
                        <div class="description">
                            overall city score
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

PXS/ui/templates/pxs/map.html
{% load static %}

<div id="map-wrapper">
    <div id="map-inner-wrapper">
        <div id="map-close">
            <a href=""><i class="fas fa-times"></i></a>
        </div>
        <div id="map"></div>
    </div>
    <div id="alert-wrapper">
        <div id="alert">Alert</div>
    </div>
    <script type="text/javascript">
        var cantonsGeoJsonUrl = "{% url 'ui:countryCantons' 51701 %}";
        var polygonGeoJsonUrl = "{% url 'ui:polygon' %}";
    </script>
</div>

PXS/ui/templates/pxs/menu.html
<div id="header">
    <div class="title">
        <h1>PXS 2018</h1>
        <h2>A project by Serge Morel</h2>
    </div>
    <nav>
        <a href="{% url 'ui:index' %}" class="selected">Home</a>
        <a href="{% url 'ui:ranking' %}">Ranking</a>
        <a href="{% url 'ui:index' %}">About</a>
    </nav>
</div>

PXS/ui/templates/pxs/ranking.html
{% extends "pxs/base.html" %}

{% block content %}

{% endblock %}